Add MergeTwoSortedArray Problem
iShayann/DSA_sorcery pull request #8
Opened 2023-10-28 23:34 UTC by HarshvMahawar

Please do add Hacktoberfest labels, thanks :)

2023-10-29 19:56 UTC, iShayann requested changes
Firstly inside the mergetwosortedarrays program folder you should make two files named problem.md (where you have to put the problem from leetcode with link) and along with that you also have to add a solution.py with a valid solution that passes all test cases. Please upload folders with  problem.md and solution.py files next time !

2023-10-30 15:41 UTC, iShayann requested changes
Please do all the changes in one pull and then submit a valid pr request.Pr Request incomplete: added solution.py without problem.md

2023-10-30 17:07 UTC, HarshvMahawar commented
I have done all the changes in one pull request only (for each new problem added) , what am I supposed to do?

2023-10-30 17:49 UTC, iShayann approved these changes

2023-10-30 17:49 UTC, merged